AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template for a PDF field discovery function.

Resources:
  PdfControlDiscoveryApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: PdfControlDiscoveryApi  # Renaming the API to be more descriptive
      StageName: Prod

  pdfControlDiscoveryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: pdf_control_discovery.lambda_handler
      Runtime: python3.12
      MemorySize: 128
      Timeout: 3
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref PdfControlDiscoveryApi  # Reference the renamed API
            Path: /pdf-control-discovery
            Method: GET
            Auth:
              ApiKeyRequired: true
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:HeadObject
            Resource: arn:aws:s3:::aws-sam-cli-managed-default-samclisourcebucket-kdvjqzoec6pg/*  # Make sure to replace with your actual bucket name

  PdfControlDiscoveryUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: PdfControlDiscoveryApiProdStage  # Ensure this is created first
    Properties:
      ApiStages:
        - ApiId: !Ref PdfControlDiscoveryApi  # Reference the renamed API
          Stage: Prod  # Ensure this stage exists
      UsagePlanName: PdfControlDiscoveryUsagePlan
      Description: Usage plan for the PDF control discovery function
      Throttle:
        RateLimit: 10
        BurstLimit: 2

  PdfControlDiscoveryApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: PdfControlDiscoveryApiProdStage  # Ensure this is created first
    Properties:
      Enabled: true
      Name: PdfControlDiscoveryApiKey
      StageKeys:
        - RestApiId: !Ref PdfControlDiscoveryApi  # Reference the renamed API
          StageName: Prod  # Ensure this stage exists

  PdfControlDiscoveryUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref PdfControlDiscoveryApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref PdfControlDiscoveryUsagePlan

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${PdfControlDiscoveryApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
